#ifndef ADVANCEDSETTING_GLOBAL_H
#define ADVANCEDSETTING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ADVANCEDSETTING_LIBRARY)
#  define ADVANCEDSETTING_EXPORT Q_DECL_EXPORT
#else
#  define ADVANCEDSETTING_EXPORT Q_DECL_IMPORT
#endif

#endif // ADVANCEDSETTING_GLOBAL_H
