MAXCONFIG_VERSION = 3.0.4
MAXCONFIG_COMPAT_VERSION = 3.0.0
MAXCONFIG_DISPLAY_VERSION = 3.0.4
MAXCONFIG_COPYRIGHT_YEAR = 2021

PRO_DISPLAY_NAME = MaxConfig
PRO_ID = MaxConfig
PRO_CASED_ID = MaxConfig

FORMS +=

HEADERS +=

SOURCES +=

