include($$replace(_PRO_FILE_PWD_, ([^/]+$), \\1/\\1_dependencies.pri))
TARGET = $$QTC_LIB_NAME

include(../MaxConfig.pri)

win32 {
    DLLDESTDIR = $$PRO_APP_PATH
}

DESTDIR = $$PRO_LIBRARY_PATH
LIBS *= -L$$PRO_LIBRARY_PATH
TARGET = $$qtLibraryTargetName($$TARGET)

TEMPLATE = lib
CONFIG += shared dll


INCLUDEPATH += $$LBUSINESSLIB_INCLUDE/LAPI_Control
message(1111111111= $$LBUSINESSLIB_INCLUDE/LAPI_Control)
INCLUDEPATH += $$LBUSINESSLIB_INCLUDE/LBL_SenderCardItem
INCLUDEPATH += $$LBUSINESSLIB_INCLUDE/LBL_CommunicatEngine
INCLUDEPATH += $$LBUSINESSLIB_INCLUDE/LBL_Control
INCLUDEPATH += $$LBUSINESSLIB_INCLUDE/LBL_Core
INCLUDEPATH += $$LBUSINESSLIB_INCLUDE/LBL_Advanced
